version: "3.9"
services:
  web:
    build: .
    ports:
      - "8083:8080"
    container_name: api
  db:
    image: postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
    container_name: database